# M365TenantHygiene is free and MIT-licensed — the full audit, HTML report and CSV exports,
# and every check. Pro (SARIF, baseline) and sponsorship keep it maintained.
github: [earbona23]
patreon: EduardArbona
